#include <cstdio>

int main()
{
	int n;
	scanf("%d", &n);
    
	switch(n)
	{
		case 1: printf("Bulbasaur\nGrass Poison"); break;
		case 2: printf("Ivysaur\nGrass Poison"); break;
		case 3: printf("Venusaur\nGrass Poison"); break;
		case 4: printf("Charmander\nFire"); break;
		case 5: printf("Charmeleon\nFire"); break;
		case 6: printf("Charizard\nFire Flying"); break;
		case 7: printf("Squirtle\nWater"); break;
		case 8: printf("Wartortle\nWater"); break;
		case 9: printf("Blastoise\nWater"); break;
		case 10: printf("Caterpie\nBug"); break;
		case 11: printf("Metapod\nBug"); break;
		case 12: printf("Butterfree\nBug Flying"); break;
		case 13: printf("Weedle\nBug Poison"); break;
		case 14: printf("Kakuna\nBug Poison"); break;
		case 15: printf("Beedrill\nBug Poison"); break;
		case 16: printf("Pidgey\nNormal Flying"); break;
		case 17: printf("Pidgeotto\nNormal Flying"); break;
		case 18: printf("Pidgeot\nNormal Flying"); break;
		case 19: printf("Rattata\nNormal"); break;
		case 20: printf("Raticate\nNormal"); break;
		case 21: printf("Spearow\nNormal Flying"); break;
		case 22: printf("Fearow\nNormal Flying"); break;
		case 23: printf("Ekans\nPoison"); break;
		case 24: printf("Arbok\nPoison"); break;
		case 25: printf("Pikachu\nElectric"); break;
		case 26: printf("Raichu\nElectric"); break;
		case 27: printf("Sandshrew\nGround"); break;
		case 28: printf("Sandslash\nGround"); break;
		case 29: printf("Nidoran♀\nPoison"); break;
		case 30: printf("Nidorina\nPoison"); break;
		case 31: printf("Nidoqueen\nPoison Ground"); break;
		case 32: printf("Nidoran♂\nPoison"); break;
		case 33: printf("Nidorino\nPoison"); break;
		case 34: printf("Nidoking\nPoison Ground"); break;
		case 35: printf("Clefairy\nFairy"); break;
		case 36: printf("Clefable\nFairy"); break;
		case 37: printf("Vulpix\nFire"); break;
		case 38: printf("Ninetales\nFire"); break;
		case 39: printf("Jigglypuff\nNormal Fairy"); break;
		case 40: printf("Wigglytuff\nNormal Fairy"); break;
		case 41: printf("Zubat\nPoison Flying"); break;
		case 42: printf("Golbat\nPoison Flying"); break;
		case 43: printf("Oddish\nGrass Poison"); break;
		case 44: printf("Gloom\nGrass Poison"); break;
		case 45: printf("Vileplume\nGrass Poison"); break;
		case 46: printf("Paras\nBug Grass"); break;
		case 47: printf("Parasect\nBug Grass"); break;
		case 48: printf("Venonat\nBug Poison"); break;
		case 49: printf("Venomoth\nBug Poison"); break;
		case 50: printf("Diglett\nGround"); break;
		case 51: printf("Dugtrio\nGround"); break;
		case 52: printf("Meowth\nNormal"); break;
		case 53: printf("Persian\nNormal"); break;
		case 54: printf("Psyduck\nWater"); break;
		case 55: printf("Golduck\nWater"); break;
		case 56: printf("Mankey\nFighting"); break;
		case 57: printf("Primeape\nFighting"); break;
		case 58: printf("Growlithe\nFire"); break;
		case 59: printf("Arcanine\nFire"); break;
		case 60: printf("Poliwag\nWater"); break;
		case 61: printf("Poliwhirl\nWater"); break;
		case 62: printf("Poliwrath\nWater Fighting"); break;
		case 63: printf("Abra\nPsychic"); break;
		case 64: printf("Kadabra\nPsychic"); break;
		case 65: printf("Alakazam\nPsychic"); break;
		case 66: printf("Machop\nFighting"); break;
		case 67: printf("Machoke\nFighting"); break;
		case 68: printf("Machamp\nFighting"); break;
		case 69: printf("Bellsprout\nGrass Poison"); break;
		case 70: printf("Weepinbell\nGrass Poison"); break;
		case 71: printf("Victreebel\nGrass Poison"); break;
		case 72: printf("Tentacool\nWater Poison"); break;
		case 73: printf("Tentacruel\nWater Poison"); break;
		case 74: printf("Geodude\nRock Ground"); break;
		case 75: printf("Graveler\nRock Ground"); break;
		case 76: printf("Golem\nRock Ground"); break;
		case 77: printf("Ponyta\nFire"); break;
		case 78: printf("Rapidash\nFire"); break;
		case 79: printf("Slowpoke\nWater Psychic"); break;
		case 80: printf("Slowbro\nWater Psychic"); break;
		case 81: printf("Magnemite\nElectric Steel"); break;
		case 82: printf("Magneton\nElectric Steel"); break;
		case 83: printf("Farfetch'd\nNormal Flying"); break;
		case 84: printf("Doduo\nNormal Flying"); break;
		case 85: printf("Dodrio\nNormal Flying"); break;
		case 86: printf("Seel\nWater"); break;
		case 87: printf("Dewgong\nWater Ice"); break;
		case 88: printf("Grimer\nPoison"); break;
		case 89: printf("Muk\nPoison"); break;
		case 90: printf("Shellder\nWater"); break;
		case 91: printf("Cloyster\nWater Ice"); break;
		case 92: printf("Gastly\nGhost Poison"); break;
		case 93: printf("Haunter\nGhost Poison"); break;
		case 94: printf("Gengar\nGhost Poison"); break;
		case 95: printf("Onix\nRock Ground"); break;
		case 96: printf("Drowzee\nPsychic"); break;
		case 97: printf("Hypno\nPsychic"); break;
		case 98: printf("Krabby\nWater"); break;
		case 99: printf("Kingler\nWater"); break;
		case 100: printf("Voltorb\nElectric"); break;
		case 101: printf("Electrode\nElectric"); break;
		case 102: printf("Exeggcute\nGrass Psychic"); break;
		case 103: printf("Exeggutor\nGrass Psychic"); break;
		case 104: printf("Cubone\nGround"); break;
		case 105: printf("Marowak\nGround"); break;
		case 106: printf("Hitmonlee\nFighting"); break;
		case 107: printf("Hitmonchan\nFighting"); break;
		case 108: printf("Lickitung\nNormal"); break;
		case 109: printf("Koffing\nPoison"); break;
		case 110: printf("Weezing\nPoison"); break;
		case 111: printf("Rhyhorn\nGround Rock"); break;
		case 112: printf("Rhydon\nGround Rock"); break;
		case 113: printf("Chansey\nNormal"); break;
		case 114: printf("Tangela\nGrass"); break;
		case 115: printf("Kangaskhan\nNormal"); break;
		case 116: printf("Horsea\nWater"); break;
		case 117: printf("Seadra\nWater"); break;
		case 118: printf("Goldeen\nWater"); break;
		case 119: printf("Seaking\nWater"); break;
		case 120: printf("Staryu\nWater"); break;
		case 121: printf("Starmie\nWater Psychic"); break;
		case 122: printf("Mr. Mime\nPsychic Fairy"); break;
		case 123: printf("Scyther\nBug Flying"); break;
		case 124: printf("Jynx\nIce Psychic"); break;
		case 125: printf("Electabuzz\nElectric"); break;
		case 126: printf("Magmar\nFire"); break;
		case 127: printf("Pinsir\nBug"); break;
		case 128: printf("Tauros\nNormal"); break;
		case 129: printf("Magikarp\nWater"); break;
		case 130: printf("Gyarados\nWater Flying"); break;
		case 131: printf("Lapras\nWater Ice"); break;
		case 132: printf("Ditto\nNormal"); break;
		case 133: printf("Eevee\nNormal"); break;
		case 134: printf("Vaporeon\nWater"); break;
		case 135: printf("Jolteon\nElectric"); break;
		case 136: printf("Flareon\nFire"); break;
		case 137: printf("Porygon\nNormal"); break;
		case 138: printf("Omanyte\nRock Water"); break;
		case 139: printf("Omastar\nRock Water"); break;
		case 140: printf("Kabuto\nRock Water"); break;
		case 141: printf("Kabutops\nRock Water"); break;
		case 142: printf("Aerodactyl\nRock Flying"); break;
		case 143: printf("Snorlax\nNormal"); break;
		case 144: printf("Articuno\nIce Flying"); break;
		case 145: printf("Zapdos\nElectric Flying"); break;
		case 146: printf("Moltres\nFire Flying"); break;
		case 147: printf("Dratini\nDragon"); break;
		case 148: printf("Dragonair\nDragon"); break;
		case 149: printf("Dragonite\nDragon Flying"); break;
		case 150: printf("Mewtwo\nPsychic"); break;
		case 151: printf("Mew\nPsychic"); break;
		case 152: printf("Chikorita\nGrass"); break;
		case 153: printf("Bayleef\nGrass"); break;
		case 154: printf("Meganium\nGrass"); break;
		case 155: printf("Cyndaquil\nFire"); break;
		case 156: printf("Quilava\nFire"); break;
		case 157: printf("Typhlosion\nFire"); break;
		case 158: printf("Totodile\nWater"); break;
		case 159: printf("Croconaw\nWater"); break;
		case 160: printf("Feraligatr\nWater"); break;
		case 161: printf("Sentret\nNormal"); break;
		case 162: printf("Furret\nNormal"); break;
		case 163: printf("Hoothoot\nNormal Flying"); break;
		case 164: printf("Noctowl\nNormal Flying"); break;
		case 165: printf("Ledyba\nBug Flying"); break;
		case 166: printf("Ledian\nBug Flying"); break;
		case 167: printf("Spinarak\nBug Poison"); break;
		case 168: printf("Ariados\nBug Poison"); break;
		case 169: printf("Crobat\nPoison Flying"); break;
		case 170: printf("Chinchou\nWater Electric"); break;
		case 171: printf("Lanturn\nWater Electric"); break;
		case 172: printf("Pichu\nElectric"); break;
		case 173: printf("Cleffa\nFairy"); break;
		case 174: printf("Igglybuff\nNormal Fairy"); break;
		case 175: printf("Togepi\nFairy"); break;
		case 176: printf("Togetic\nFairy Flying"); break;
		case 177: printf("Natu\nPsychic Flying"); break;
		case 178: printf("Xatu\nPsychic Flying"); break;
		case 179: printf("Mareep\nElectric"); break;
		case 180: printf("Flaaffy\nElectric"); break;
		case 181: printf("Ampharos\nElectric"); break;
		case 182: printf("Bellossom\nGrass"); break;
		case 183: printf("Marill\nWater Fairy"); break;
		case 184: printf("Azumarill\nWater Fairy"); break;
		case 185: printf("Sudowoodo\nRock"); break;
		case 186: printf("Politoed\nWater"); break;
		case 187: printf("Hoppip\nGrass Flying"); break;
		case 188: printf("Skiploom\nGrass Flying"); break;
		case 189: printf("Jumpluff\nGrass Flying"); break;
		case 190: printf("Aipom\nNormal"); break;
		case 191: printf("Sunkern\nGrass"); break;
		case 192: printf("Sunflora\nGrass"); break;
		case 193: printf("Yanma\nBug Flying"); break;
		case 194: printf("Wooper\nWater Ground"); break;
		case 195: printf("Quagsire\nWater Ground"); break;
		case 196: printf("Espeon\nPsychic"); break;
		case 197: printf("Umbreon\nDark"); break;
		case 198: printf("Murkrow\nDark Flying"); break;
		case 199: printf("Slowking\nWater Psychic"); break;
		case 200: printf("Misdreavus\nGhost"); break;
		case 201: printf("Unown\nPsychic"); break;
		case 202: printf("Wobbuffet\nPsychic"); break;
		case 203: printf("Girafarig\nNormal Psychic"); break;
		case 204: printf("Pineco\nBug"); break;
		case 205: printf("Forretress\nBug Steel"); break;
		case 206: printf("Dunsparce\nNormal"); break;
		case 207: printf("Gligar\nGround Flying"); break;
		case 208: printf("Steelix\nSteel Ground"); break;
		case 209: printf("Snubbull\nFairy"); break;
		case 210: printf("Granbull\nFairy"); break;
		case 211: printf("Qwilfish\nWater Poison"); break;
		case 212: printf("Scizor\nBug Steel"); break;
		case 213: printf("Shuckle\nBug Rock"); break;
		case 214: printf("Heracross\nBug Fighting"); break;
		case 215: printf("Sneasel\nDark Ice"); break;
		case 216: printf("Teddiursa\nNormal"); break;
		case 217: printf("Ursaring\nNormal"); break;
		case 218: printf("Slugma\nFire"); break;
		case 219: printf("Magcargo\nFire Rock"); break;
		case 220: printf("Swinub\nIce Ground"); break;
		case 221: printf("Piloswine\nIce Ground"); break;
		case 222: printf("Corsola\nWater Rock"); break;
		case 223: printf("Remoraid\nWater"); break;
		case 224: printf("Octillery\nWater"); break;
		case 225: printf("Delibird\nIce Flying"); break;
		case 226: printf("Mantine\nWater Flying"); break;
		case 227: printf("Skarmory\nSteel Flying"); break;
		case 228: printf("Houndour\nDark Fire"); break;
		case 229: printf("Houndoom\nDark Fire"); break;
		case 230: printf("Kingdra\nWater Dragon"); break;
		case 231: printf("Phanpy\nGround"); break;
		case 232: printf("Donphan\nGround"); break;
		case 233: printf("Porygon2\nNormal"); break;
		case 234: printf("Stantler\nNormal"); break;
		case 235: printf("Smeargle\nNormal"); break;
		case 236: printf("Tyrogue\nFighting"); break;
		case 237: printf("Hitmontop\nFighting"); break;
		case 238: printf("Smoochum\nIce Psychic"); break;
		case 239: printf("Elekid\nElectric"); break;
		case 240: printf("Magby\nFire"); break;
		case 241: printf("Miltank\nNormal"); break;
		case 242: printf("Blissey\nNormal"); break;
		case 243: printf("Raikou\nElectric"); break;
		case 244: printf("Entei\nFire"); break;
		case 245: printf("Suicune\nWater"); break;
		case 246: printf("Larvitar\nRock Ground"); break;
		case 247: printf("Pupitar\nRock Ground"); break;
		case 248: printf("Tyranitar\nRock Dark"); break;
		case 249: printf("Lugia\nPsychic Flying"); break;
		case 250: printf("Ho-oh\nFire Flying"); break;
		case 251: printf("Celebi\nPsychic Grass"); break;
		case 252: printf("Treecko\nGrass"); break;
		case 253: printf("Grovyle\nGrass"); break;
		case 254: printf("Sceptile\nGrass"); break;
		case 255: printf("Torchic\nFire"); break;
		case 256: printf("Combusken\nFire Fighting"); break;
		case 257: printf("Blaziken\nFire Fighting"); break;
		case 258: printf("Mudkip\nWater"); break;
		case 259: printf("Marshtomp\nWater Ground"); break;
		case 260: printf("Swampert\nWater Ground"); break;
		case 261: printf("Poochyena\nDark"); break;
		case 262: printf("Mightyena\nDark"); break;
		case 263: printf("Zigzagoon\nNormal"); break;
		case 264: printf("Linoone\nNormal"); break;
		case 265: printf("Wurmple\nBug"); break;
		case 266: printf("Silcoon\nBug"); break;
		case 267: printf("Beautifly\nBug Flying"); break;
		case 268: printf("Cascoon\nBug"); break;
		case 269: printf("Dustox\nBug Poison"); break;
		case 270: printf("Lotad\nWater Grass"); break;
		case 271: printf("Lombre\nWater Grass"); break;
		case 272: printf("Ludicolo\nWater Grass"); break;
		case 273: printf("Seedot\nGrass"); break;
		case 274: printf("Nuzleaf\nGrass Dark"); break;
		case 275: printf("Shiftry\nGrass Dark"); break;
		case 276: printf("Taillow\nNormal Flying"); break;
		case 277: printf("Swellow\nNormal Flying"); break;
		case 278: printf("Wingull\nWater Flying"); break;
		case 279: printf("Pelipper\nWater Flying"); break;
		case 280: printf("Ralts\nPsychic Fairy"); break;
		case 281: printf("Kirlia\nPsychic Fairy"); break;
		case 282: printf("Gardevoir\nPsychic Fairy"); break;
		case 283: printf("Surskit\nBug Water"); break;
		case 284: printf("Masquerain\nBug Flying"); break;
		case 285: printf("Shroomish\nGrass"); break;
		case 286: printf("Breloom\nGrass Fighting"); break;
		case 287: printf("Slakoth\nNormal"); break;
		case 288: printf("Vigoroth\nNormal"); break;
		case 289: printf("Slaking\nNormal"); break;
		case 290: printf("Nincada\nBug Ground"); break;
		case 291: printf("Ninjask\nBug Flying"); break;
		case 292: printf("Shedinja\nBug Ghost"); break;
		case 293: printf("Whismur\nNormal"); break;
		case 294: printf("Loudred\nNormal"); break;
		case 295: printf("Exploud\nNormal"); break;
		case 296: printf("Makuhita\nFighting"); break;
		case 297: printf("Hariyama\nFighting"); break;
		case 298: printf("Azurill\nNormal Fairy"); break;
		case 299: printf("Nosepass\nRock"); break;
		case 300: printf("Skitty\nNormal"); break;
		case 301: printf("Delcatty\nNormal"); break;
		case 302: printf("Sableye\nDark Ghost"); break;
		case 303: printf("Mawile\nSteel Fairy"); break;
		case 304: printf("Aron\nSteel Rock"); break;
		case 305: printf("Lairon\nSteel Rock"); break;
		case 306: printf("Aggron\nSteel Rock"); break;
		case 307: printf("Meditite\nFighting Psychic"); break;
		case 308: printf("Medicham\nFighting Psychic"); break;
		case 309: printf("Electrike\nElectric"); break;
		case 310: printf("Manectric\nElectric"); break;
		case 311: printf("Plusle\nElectric"); break;
		case 312: printf("Minun\nElectric"); break;
		case 313: printf("Volbeat\nBug"); break;
		case 314: printf("Illumise\nBug"); break;
		case 315: printf("Roselia\nGrass Poison"); break;
		case 316: printf("Gulpin\nPoison"); break;
		case 317: printf("Swalot\nPoison"); break;
		case 318: printf("Carvanha\nWater Dark"); break;
		case 319: printf("Sharpedo\nWater Dark"); break;
		case 320: printf("Wailmer\nWater"); break;
		case 321: printf("Wailord\nWater"); break;
		case 322: printf("Numel\nFire Ground"); break;
		case 323: printf("Camerupt\nFire Ground"); break;
		case 324: printf("Torkoal\nFire"); break;
		case 325: printf("Spoink\nPsychic"); break;
		case 326: printf("Grumpig\nPsychic"); break;
		case 327: printf("Spinda\nNormal"); break;
		case 328: printf("Trapinch\nGround"); break;
		case 329: printf("Vibrava\nGround Dragon"); break;
		case 330: printf("Flygon\nGround Dragon"); break;
		case 331: printf("Cacnea\nGrass"); break;
		case 332: printf("Cacturne\nGrass Dark"); break;
		case 333: printf("Swablu\nNormal Flying"); break;
		case 334: printf("Altaria\nDragon Flying"); break;
		case 335: printf("Zangoose\nNormal"); break;
		case 336: printf("Seviper\nPoison"); break;
		case 337: printf("Lunatone\nRock Psychic"); break;
		case 338: printf("Solrock\nRock Psychic"); break;
		case 339: printf("Barboach\nWater Ground"); break;
		case 340: printf("Whiscash\nWater Ground"); break;
		case 341: printf("Corphish\nWater"); break;
		case 342: printf("Crawdaunt\nWater Dark"); break;
		case 343: printf("Baltoy\nGround Psychic"); break;
		case 344: printf("Claydol\nGround Psychic"); break;
		case 345: printf("Lileep\nRock Grass"); break;
		case 346: printf("Cradily\nRock Grass"); break;
		case 347: printf("Anorith\nRock Bug"); break;
		case 348: printf("Armaldo\nRock Bug"); break;
		case 349: printf("Feebas\nWater"); break;
		case 350: printf("Milotic\nWater"); break;
		case 351: printf("Castform\nNormal"); break;
		case 352: printf("Kecleon\nNormal"); break;
		case 353: printf("Shuppet\nGhost"); break;
		case 354: printf("Banette\nGhost"); break;
		case 355: printf("Duskull\nGhost"); break;
		case 356: printf("Dusclops\nGhost"); break;
		case 357: printf("Tropius\nGrass Flying"); break;
		case 358: printf("Chimecho\nPsychic"); break;
		case 359: printf("Absol\nDark"); break;
		case 360: printf("Wynaut\nPsychic"); break;
		case 361: printf("Snorunt\nIce"); break;
		case 362: printf("Glalie\nIce"); break;
		case 363: printf("Spheal\nIce Water"); break;
		case 364: printf("Sealeo\nIce Water"); break;
		case 365: printf("Walrein\nIce Water"); break;
		case 366: printf("Clamperl\nWater"); break;
		case 367: printf("Huntail\nWater"); break;
		case 368: printf("Gorebyss\nWater"); break;
		case 369: printf("Relicanth\nWater Rock"); break;
		case 370: printf("Luvdisc\nWater"); break;
		case 371: printf("Bagon\nDragon"); break;
		case 372: printf("Shelgon\nDragon"); break;
		case 373: printf("Salamence\nDragon Flying"); break;
		case 374: printf("Beldum\nSteel Psychic"); break;
		case 375: printf("Metang\nSteel Psychic"); break;
		case 376: printf("Metagross\nSteel Psychic"); break;
		case 377: printf("Regirock\nRock"); break;
		case 378: printf("Regice\nIce"); break;
		case 379: printf("Registeel\nSteel"); break;
		case 380: printf("Latias\nDragon Psychic"); break;
		case 381: printf("Latios\nDragon Psychic"); break;
		case 382: printf("Kyogre\nWater"); break;
		case 383: printf("Groudon\nGround"); break;
		case 384: printf("Rayquaza\nDragon Flying"); break;
		case 385: printf("Jirachi\nSteel Psychic"); break;
		case 386: printf("Deoxys\nPsychic"); break;
		case 387: printf("Turtwig\nGrass"); break;
		case 388: printf("Grotle\nGrass"); break;
		case 389: printf("Torterra\nGrass Ground"); break;
		case 390: printf("Chimchar\nFire"); break;
		case 391: printf("Monferno\nFire Fighting"); break;
		case 392: printf("Infernape\nFire Fighting"); break;
		case 393: printf("Piplup\nWater"); break;
		case 394: printf("Prinplup\nWater"); break;
		case 395: printf("Empoleon\nWater Steel"); break;
		case 396: printf("Starly\nNormal Flying"); break;
		case 397: printf("Staravia\nNormal Flying"); break;
		case 398: printf("Staraptor\nNormal Flying"); break;
		case 399: printf("Bidoof\nNormal"); break;
		case 400: printf("Bibarel\nNormal Water"); break;
		case 401: printf("Kricketot\nBug"); break;
		case 402: printf("Kricketune\nBug"); break;
		case 403: printf("Shinx\nElectric"); break;
		case 404: printf("Luxio\nElectric"); break;
		case 405: printf("Luxray\nElectric"); break;
		case 406: printf("Budew\nGrass Poison"); break;
		case 407: printf("Roserade\nGrass Poison"); break;
		case 408: printf("Cranidos\nRock"); break;
		case 409: printf("Rampardos\nRock"); break;
		case 410: printf("Shieldon\nRock Steel"); break;
		case 411: printf("Bastiodon\nRock Steel"); break;
		case 412: printf("Burmy\nBug"); break;
		case 413: printf("Wormadam\nBug Grass"); break;
		case 414: printf("Mothim\nBug Flying"); break;
		case 415: printf("Combee\nBug Flying"); break;
		case 416: printf("Vespiquen\nBug Flying"); break;
		case 417: printf("Pachirisu\nElectric"); break;
		case 418: printf("Buizel\nWater"); break;
		case 419: printf("Floatzel\nWater"); break;
		case 420: printf("Cherubi\nGrass"); break;
		case 421: printf("Cherrim\nGrass"); break;
		case 422: printf("Shellos\nWater"); break;
		case 423: printf("Gastrodon\nWater Ground"); break;
		case 424: printf("Ambipom\nNormal"); break;
		case 425: printf("Drifloon\nGhost Flying"); break;
		case 426: printf("Drifblim\nGhost Flying"); break;
		case 427: printf("Buneary\nNormal"); break;
		case 428: printf("Lopunny\nNormal"); break;
		case 429: printf("Mismagius\nGhost"); break;
		case 430: printf("Honchkrow\nDark Flying"); break;
		case 431: printf("Glameow\nNormal"); break;
		case 432: printf("Purugly\nNormal"); break;
		case 433: printf("Chingling\nPsychic"); break;
		case 434: printf("Stunky\nPoison Dark"); break;
		case 435: printf("Skuntank\nPoison Dark"); break;
		case 436: printf("Bronzor\nSteel Psychic"); break;
		case 437: printf("Bronzong\nSteel Psychic"); break;
		case 438: printf("Bonsly\nRock"); break;
		case 439: printf("Mime Jr.\nPsychic Fairy"); break;
		case 440: printf("Happiny\nNormal"); break;
		case 441: printf("Chatot\nNormal Flying"); break;
		case 442: printf("Spiritomb\nGhost Dark"); break;
		case 443: printf("Gible\nDragon Ground"); break;
		case 444: printf("Gabite\nDragon Ground"); break;
		case 445: printf("Garchomp\nDragon Ground"); break;
		case 446: printf("Munchlax\nNormal"); break;
		case 447: printf("Riolu\nFighting"); break;
		case 448: printf("Lucario\nFighting Steel"); break;
		case 449: printf("Hippopotas\nGround"); break;
		case 450: printf("Hippowdon\nGround"); break;
		case 451: printf("Skorupi\nPoison Bug"); break;
		case 452: printf("Drapion\nPoison Dark"); break;
		case 453: printf("Croagunk\nPoison Fighting"); break;
		case 454: printf("Toxicroak\nPoison Fighting"); break;
		case 455: printf("Carnivine\nGrass"); break;
		case 456: printf("Finneon\nWater"); break;
		case 457: printf("Lumineon\nWater"); break;
		case 458: printf("Mantyke\nWater Flying"); break;
		case 459: printf("Snover\nGrass Ice"); break;
		case 460: printf("Abomasnow\nGrass Ice"); break;
		case 461: printf("Weavile\nDark Ice"); break;
		case 462: printf("Magnezone\nElectric Steel"); break;
		case 463: printf("Lickilicky\nNormal"); break;
		case 464: printf("Rhyperior\nGround Rock"); break;
		case 465: printf("Tangrowth\nGrass"); break;
		case 466: printf("Electivire\nElectric"); break;
		case 467: printf("Magmortar\nFire"); break;
		case 468: printf("Togekiss\nFairy Flying"); break;
		case 469: printf("Yanmega\nBug Flying"); break;
		case 470: printf("Leafeon\nGrass"); break;
		case 471: printf("Glaceon\nIce"); break;
		case 472: printf("Gliscor\nGround Flying"); break;
		case 473: printf("Mamoswine\nIce Ground"); break;
		case 474: printf("Porygon-Z\nNormal"); break;
		case 475: printf("Gallade\nPsychic Fighting"); break;
		case 476: printf("Probopass\nRock Steel"); break;
		case 477: printf("Dusknoir\nGhost"); break;
		case 478: printf("Froslass\nIce Ghost"); break;
		case 479: printf("Rotom\nElectric Ghost"); break;
		case 480: printf("Uxie\nPsychic"); break;
		case 481: printf("Mesprit\nPsychic"); break;
		case 482: printf("Azelf\nPsychic"); break;
		case 483: printf("Dialga\nSteel Dragon"); break;
		case 484: printf("Palkia\nWater Dragon"); break;
		case 485: printf("Heatran\nFire Steel"); break;
		case 486: printf("Regigigas\nNormal"); break;
		case 487: printf("Giratina\nGhost Dragon"); break;
		case 488: printf("Cresselia\nPsychic"); break;
		case 489: printf("Phione\nWater"); break;
		case 490: printf("Manaphy\nWater"); break;
		case 491: printf("Darkrai\nDark"); break;
		case 492: printf("Shaymin\nGrass"); break;
		case 493: printf("Arceus\nNormal"); break;
		case 494: printf("Victini\nPsychic Fire"); break;
		case 495: printf("Snivy\nGrass"); break;
		case 496: printf("Servine\nGrass"); break;
		case 497: printf("Serperior\nGrass"); break;
		case 498: printf("Tepig\nFire"); break;
		case 499: printf("Pignite\nFire Fighting"); break;
		case 500: printf("Emboar\nFire Fighting"); break;
		case 501: printf("Oshawott\nWater"); break;
		case 502: printf("Dewott\nWater"); break;
		case 503: printf("Samurott\nWater"); break;
		case 504: printf("Patrat\nNormal"); break;
		case 505: printf("Watchog\nNormal"); break;
		case 506: printf("Lillipup\nNormal"); break;
		case 507: printf("Herdier\nNormal"); break;
		case 508: printf("Stoutland\nNormal"); break;
		case 509: printf("Purrloin\nDark"); break;
		case 510: printf("Liepard\nDark"); break;
		case 511: printf("Pansage\nGrass"); break;
		case 512: printf("Simisage\nGrass"); break;
		case 513: printf("Pansear\nFire"); break;
		case 514: printf("Simisear\nFire"); break;
		case 515: printf("Panpour\nWater"); break;
		case 516: printf("Simipour\nWater"); break;
		case 517: printf("Munna\nPsychic"); break;
		case 518: printf("Musharna\nPsychic"); break;
		case 519: printf("Pidove\nNormal Flying"); break;
		case 520: printf("Tranquill\nNormal Flying"); break;
		case 521: printf("Unfezant\nNormal Flying"); break;
		case 522: printf("Blitzle\nElectric"); break;
		case 523: printf("Zebstrika\nElectric"); break;
		case 524: printf("Roggenrola\nRock"); break;
		case 525: printf("Boldore\nRock"); break;
		case 526: printf("Gigalith\nRock"); break;
		case 527: printf("Woobat\nPsychic Flying"); break;
		case 528: printf("Swoobat\nPsychic Flying"); break;
		case 529: printf("Drilbur\nGround"); break;
		case 530: printf("Excadrill\nGround Steel"); break;
		case 531: printf("Audino\nNormal"); break;
		case 532: printf("Timburr\nFighting"); break;
		case 533: printf("Gurdurr\nFighting"); break;
		case 534: printf("Conkeldurr\nFighting"); break;
		case 535: printf("Tympole\nWater"); break;
		case 536: printf("Palpitoad\nWater Ground"); break;
		case 537: printf("Seismitoad\nWater Ground"); break;
		case 538: printf("Throh\nFighting"); break;
		case 539: printf("Sawk\nFighting"); break;
		case 540: printf("Sewaddle\nBug Grass"); break;
		case 541: printf("Swadloon\nBug Grass"); break;
		case 542: printf("Leavanny\nBug Grass"); break;
		case 543: printf("Venipede\nBug Poison"); break;
		case 544: printf("Whirlipede\nBug Poison"); break;
		case 545: printf("Scolipede\nBug Poison"); break;
		case 546: printf("Cottonee\nGrass Fairy"); break;
		case 547: printf("Whimsicott\nGrass Fairy"); break;
		case 548: printf("Petilil\nGrass"); break;
		case 549: printf("Lilligant\nGrass"); break;
		case 550: printf("Basculin\nWater"); break;
		case 551: printf("Sandile\nGround Dark"); break;
		case 552: printf("Krokorok\nGround Dark"); break;
		case 553: printf("Krookodile\nGround Dark"); break;
		case 554: printf("Darumaka\nFire"); break;
		case 555: printf("Darmanitan\nFire"); break;
		case 556: printf("Maractus\nGrass"); break;
		case 557: printf("Dwebble\nBug Rock"); break;
		case 558: printf("Crustle\nBug Rock"); break;
		case 559: printf("Scraggy\nDark Fighting"); break;
		case 560: printf("Scrafty\nDark Fighting"); break;
		case 561: printf("Sigilyph\nPsychic Flying"); break;
		case 562: printf("Yamask\nGhost"); break;
		case 563: printf("Cofagrigus\nGhost"); break;
		case 564: printf("Tirtouga\nWater Rock"); break;
		case 565: printf("Carracosta\nWater Rock"); break;
		case 566: printf("Archen\nRock Flying"); break;
		case 567: printf("Archeops\nRock Flying"); break;
		case 568: printf("Trubbish\nPoison"); break;
		case 569: printf("Garbodor\nPoison"); break;
		case 570: printf("Zorua\nDark"); break;
		case 571: printf("Zoroark\nDark"); break;
		case 572: printf("Minccino\nNormal"); break;
		case 573: printf("Cinccino\nNormal"); break;
		case 574: printf("Gothita\nPsychic"); break;
		case 575: printf("Gothorita\nPsychic"); break;
		case 576: printf("Gothitelle\nPsychic"); break;
		case 577: printf("Solosis\nPsychic"); break;
		case 578: printf("Duosion\nPsychic"); break;
		case 579: printf("Reuniclus\nPsychic"); break;
		case 580: printf("Ducklett\nWater Flying"); break;
		case 581: printf("Swanna\nWater Flying"); break;
		case 582: printf("Vanillite\nIce"); break;
		case 583: printf("Vanillish\nIce"); break;
		case 584: printf("Vanilluxe\nIce"); break;
		case 585: printf("Deerling\nNormal Grass"); break;
		case 586: printf("Sawsbuck\nNormal Grass"); break;
		case 587: printf("Emolga\nElectric Flying"); break;
		case 588: printf("Karrablast\nBug"); break;
		case 589: printf("Escavalier\nBug Steel"); break;
		case 590: printf("Foongus\nGrass Poison"); break;
		case 591: printf("Amoonguss\nGrass Poison"); break;
		case 592: printf("Frillish\nWater Ghost"); break;
		case 593: printf("Jellicent\nWater Ghost"); break;
		case 594: printf("Alomomola\nWater"); break;
		case 595: printf("Joltik\nBug Electric"); break;
		case 596: printf("Galvantula\nBug Electric"); break;
		case 597: printf("Ferroseed\nGrass Steel"); break;
		case 598: printf("Ferrothorn\nGrass Steel"); break;
		case 599: printf("Klink\nSteel"); break;
		case 600: printf("Klang\nSteel"); break;
		case 601: printf("Klinklang\nSteel"); break;
		case 602: printf("Tynamo\nElectric"); break;
		case 603: printf("Eelektrik\nElectric"); break;
		case 604: printf("Eelektross\nElectric"); break;
		case 605: printf("Elgyem\nPsychic"); break;
		case 606: printf("Beheeyem\nPsychic"); break;
		case 607: printf("Litwick\nGhost Fire"); break;
		case 608: printf("Lampent\nGhost Fire"); break;
		case 609: printf("Chandelure\nGhost Fire"); break;
		case 610: printf("Axew\nDragon"); break;
		case 611: printf("Fraxure\nDragon"); break;
		case 612: printf("Haxorus\nDragon"); break;
		case 613: printf("Cubchoo\nIce"); break;
		case 614: printf("Beartic\nIce"); break;
		case 615: printf("Cryogonal\nIce"); break;
		case 616: printf("Shelmet\nBug"); break;
		case 617: printf("Accelgor\nBug"); break;
		case 618: printf("Stunfisk\nElectric Ground"); break;
		case 619: printf("Mienfoo\nFighting"); break;
		case 620: printf("Mienshao\nFighting"); break;
		case 621: printf("Druddigon\nDragon"); break;
		case 622: printf("Golett\nGround Ghost"); break;
		case 623: printf("Golurk\nGround Ghost"); break;
		case 624: printf("Pawniard\nDark Steel"); break;
		case 625: printf("Bisharp\nDark Steel"); break;
		case 626: printf("Bouffalant\nNormal"); break;
		case 627: printf("Rufflet\nNormal Flying"); break;
		case 628: printf("Braviary\nNormal Flying"); break;
		case 629: printf("Vullaby\nDark Flying"); break;
		case 630: printf("Mandibuzz\nDark Flying"); break;
		case 631: printf("Heatmor\nFire"); break;
		case 632: printf("Durant\nBug Steel"); break;
		case 633: printf("Deino\nDark Dragon"); break;
		case 634: printf("Zweilous\nDark Dragon"); break;
		case 635: printf("Hydreigon\nDark Dragon"); break;
		case 636: printf("Larvesta\nBug Fire"); break;
		case 637: printf("Volcarona\nBug Fire"); break;
		case 638: printf("Cobalion\nSteel Fighting"); break;
		case 639: printf("Terrakion\nRock Fighting"); break;
		case 640: printf("Virizion\nGrass Fighting"); break;
		case 641: printf("Tornadus\nFlying"); break;
		case 642: printf("Thundurus\nElectric Flying"); break;
		case 643: printf("Reshiram\nDragon Fire"); break;
		case 644: printf("Zekrom\nDragon Electric"); break;
		case 645: printf("Landorus\nGround Flying"); break;
		case 646: printf("Kyurem\nDragon Ice"); break;
		case 647: printf("Keldeo\nWater Fighting"); break;
		case 648: printf("Meloetta\nNormal Psychic"); break;
		case 649: printf("Genesect\nBug Steel"); break;
		case 650: printf("Chespin\nGrass"); break;
		case 651: printf("Quilladin\nGrass"); break;
		case 652: printf("Chesnaught\nGrass Fighting"); break;
		case 653: printf("Fennekin\nFire"); break;
		case 654: printf("Braixen\nFire"); break;
		case 655: printf("Delphox\nFire Psychic"); break;
		case 656: printf("Froakie\nWater"); break;
		case 657: printf("Frogadier\nWater"); break;
		case 658: printf("Greninja\nWater Dark"); break;
		case 659: printf("Bunnelby\nNormal"); break;
		case 660: printf("Diggersby\nNormal Ground"); break;
		case 661: printf("Fletchling\nNormal Flying"); break;
		case 662: printf("Fletchinder\nFire Flying"); break;
		case 663: printf("Talonflame\nFire Flying"); break;
		case 664: printf("Scatterbug\nBug"); break;
		case 665: printf("Spewpa\nBug"); break;
		case 666: printf("Vivillon\nBug Flying"); break;
		case 667: printf("Litleo\nFire Normal"); break;
		case 668: printf("Pyroar\nFire Normal"); break;
		case 669: printf("Flabébé\nFairy"); break;
		case 670: printf("Floette\nFairy"); break;
		case 671: printf("Florges\nFairy"); break;
		case 672: printf("Skiddo\nGrass"); break;
		case 673: printf("Gogoat\nGrass"); break;
		case 674: printf("Pancham\nFighting"); break;
		case 675: printf("Pangoro\nFighting Dark"); break;
		case 676: printf("Furfrou\nNormal"); break;
		case 677: printf("Espurr\nPsychic"); break;
		case 678: printf("Meowstic\nPsychic"); break;
		case 679: printf("Honedge\nSteel Ghost"); break;
		case 680: printf("Doublade\nSteel Ghost"); break;
		case 681: printf("Aegislash\nSteel Ghost"); break;
		case 682: printf("Spritzee\nFairy"); break;
		case 683: printf("Aromatisse\nFairy"); break;
		case 684: printf("Swirlix\nFairy"); break;
		case 685: printf("Slurpuff\nFairy"); break;
		case 686: printf("Inkay\nDark Psychic"); break;
		case 687: printf("Malamar\nDark Psychic"); break;
		case 688: printf("Binacle\nRock Water"); break;
		case 689: printf("Barbaracle\nRock Water"); break;
		case 690: printf("Skrelp\nPoison Water"); break;
		case 691: printf("Dragalge\nPoison Dragon"); break;
		case 692: printf("Clauncher\nWater"); break;
		case 693: printf("Clawitzer\nWater"); break;
		case 694: printf("Helioptile\nElectric Normal"); break;
		case 695: printf("Heliolisk\nElectric Normal"); break;
		case 696: printf("Tyrunt\nRock Dragon"); break;
		case 697: printf("Tyrantrum\nRock Dragon"); break;
		case 698: printf("Amaura\nRock Ice"); break;
		case 699: printf("Aurorus\nRock Ice"); break;
		case 700: printf("Sylveon\nFairy"); break;
		case 701: printf("Hawlucha\nFighting Flying"); break;
		case 702: printf("Dedenne\nElectric Fairy"); break;
		case 703: printf("Carbink\nRock Fairy"); break;
		case 704: printf("Goomy\nDragon"); break;
		case 705: printf("Sliggoo\nDragon"); break;
		case 706: printf("Goodra\nDragon"); break;
		case 707: printf("Klefki\nSteel Fairy"); break;
		case 708: printf("Phantump\nGhost Grass"); break;
		case 709: printf("Trevenant\nGhost Grass"); break;
		case 710: printf("Pumpkaboo\nGhost Grass"); break;
		case 711: printf("Gourgeist\nGhost Grass"); break;
		case 712: printf("Bergmite\nIce"); break;
		case 713: printf("Avalugg\nIce"); break;
		case 714: printf("Noibat\nFlying Dragon"); break;
		case 715: printf("Noivern\nFlying Dragon"); break;
		case 716: printf("Xerneas\nFairy"); break;
		case 717: printf("Yveltal\nDark Flying"); break;
		case 718: printf("Zygarde\nDragon Ground"); break;
	}
	return 0;
}
